### ISSUE TITLE
Failed to install the extension

### ISSUE THREAD

**Issue by BabakAmini** [ctsstc/typio-form-recovery-reboot#5]
Due to an error I failed to install the extension:

![image](https://user-images.githubusercontent.com/85762931/223823917-13a9c230-f936-4bab-8996-7ca5016d72ba.png)

I'm also wondering if there is a way to transfer the data collected by the original extension to this new one after I managed to install it.

**Comment by Buzzmovies** [comment]
I dont mean to highjack this thread but how do I install this reboot version?

**Comment by Buzzmovies** [comment]
@BabakAmini Make sure to uninstall any previous version of this extension.

**Comment by willsheppard** [comment]
@ctsstc I also failed to install it.

I tried to load directory `typio-form-recovery-reboot/src` but got an error:

> Could not load background script 'js/background.js'.
> Could not load manifest.

**Comment by ctsstc** [comment]
> @ctsstc I also failed to install it.
> 
> I tried to load directory `typio-form-recovery-reboot/src` but got an error:
> 
> > Could not load background script 'js/background.js'.
> > Could not load manifest.

You need to run `npm run build` first. After running an `npm install`, then you should point to the build directory rather than the `src` directory.

**Comment by 0midkr** [comment]
i get this error 
![Screenshot 2024-03-28 195724](https://github.com/ctsstc/typio-form-recovery-reboot/assets/125304193/e6b1f835-0c49-49b9-84fe-bea13a53bff0)

**Comment by willsheppard** [comment]
Thanks @ctsstc, this is how I made it work for me on Ubuntu 22.04.

I ran:
```
npm run build:prod
```

This created a `dist` directory which I successfully loaded into Chrome via Extensions developer mode.

...and it works! My form inputs are saved :+1:

**Comment by ctsstc** [comment]
Opened up #10 as an action item for this.
