### ISSUE TITLE
Which fork to use?

### ISSUE THREAD

**Issue by jimmhay** [ctsstc/typio-form-recovery-reboot#9]
Hi, apologies if adding an issue is an inappropriate channel (not super familiar with gitbhub etiquette) but can you clarify whether this repository or https://github.com/tsukumijima/typio-form-recovery-reboot is a better match to the original experience? Hoping that having this answered publicly will help others coming down the same path I've come down!

**Comment by ctsstc** [comment]
Seems that there has been work done on the main branch there, so it is ahead by some. You can see the additional commits made here: https://github.com/tsukumijima/typio-form-recovery-reboot/commits/master

It doesn't seem there are many functional changes. Some coding style changes, styling, and an error message fix it sounds like. If he opens a pull request up I can get this one caught up to the work done there, or I can pull in the changes to here as well.

**Comment by jimmhay** [comment]
Got it, thanks for the reply. I've seen him say "I can't be bothered doing this" a few times so even though I installed his version before finding this, feel like yours might be more viable long term...

Thanks for keeping this magical tool alive. Watching this repo!

**Comment by ctsstc** [comment]
@jimmhay I was ready to do some major changes but then the licensing complicated things. As far as we know the original developer may no longer be around. The amount of changes I wanted to do and getting the code base up to date, at that point should just be rewritten by scratch. Upon finding the current licensing and changes that had been worked on, it really slowed down the excitement of pushing this forward at the time unfortunately.

It also doesn't make sense to potentially have folks donating to an entity that may no longer exist, but also taking that link away or changing it doesn't follow the license either.
